### ISSUE TITLE
Package maintenance.

### ISSUE THREAD

**Issue by jarrettj** [ZF-Commons/ZfcUserDoctrineORM#115]
Hi,

Good day.

Is this package ever going to be updated? It is such a key part of our system.

Regards.
Jarrett

**Comment by Kwido** [comment]
I would recommend to drop ZF-commons and create your own adapter for (Zend) Laminas\Authentication. Together with some listeners for Authorization based on your applications permissions system (acl or rbac).

Yes I ditched zf-commons a while ago, back in 2016 since I already did not get any update as there was a conflict within composer.json and didn't allow us to update Doctrine.

And if you want to continue using this package, create your own fork and start using that in your project.

**Comment by jarrettj** [comment]
Thanks Kwido. Busy migrating to PHP 7.3 and was a bit stuck in dependency hell with composer. Thank you for the feedback. Will add this to our roadmap. Regards.

**Comment by Kwido** [comment]
**Notice that I am not a maintainer or what so ever from this package!** This is just from my personal experience. We did create a fork for our company as well, due to the lackluster updates. There was no real need for this package as a lot of those things are pretty straight forward and was just a shortcut for us. Just Keep It Simple and Stupid (KISS).

Good luck with the roadmap and migration! 👍
